# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OttocashSDKDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'OTTOCashSDK', '0.10.10-beta'
  pod 'Fabric'
  pod 'Crashlytics'

  # Pods for OttocashSDKDemo

  target 'OttocashSDKDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
