# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OttocashSDKDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'OttocashSDK', :git => 'https://github.com/clappingape/OttocashSDK.git'

  # Pods for OttocashSDKDemo

  target 'OttocashSDKDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
